(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,l="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},m=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},n=m(this),p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var r={O:!0},t={};try{t.__proto__=r;q=t.O;break a}catch(a){}q=!1}p=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var u=p,w=function(a,b){a.prototype=l(b.prototype);a.prototype.constructor=a;if(u)u(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]},goog=goog||{};var x=function(a,b,c){for(var d=b/c,e,f,h,k=0;k<a.length;k++)if(e=a[k],"img"==e.tagName.toLowerCase()||"gwd-image"==e.tagName.toLowerCase())f=e.offsetWidth/e.offsetHeight,d>f?(h=c*f,f=c):(h=b,f=b/f),e.style.width=h+"px",e.style.height=f+"px"};var y=function(a,b){return window.setTimeout(a,b)};var z=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},A=function(a,b,c){c=void 0===c?null:c;var d=void 0===d?null:d;y(function(){var e=z(a,b,c);d&&d(e)},0)},B=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)},C=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=y(function(){c=null;b&&(a(),b=!1)},250))}};var D=["-ms-","-moz-","-webkit-",""];var E=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},F=function(a){if(E(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&E(a))return a;return null};var G=function(a){a=a.trim();return window.Enabler?window.Enabler.getUrl(a):a};var H=function(a){var b=document.createElement("gwd-image");b.setAttribute("source",a);return b},I=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)/^[\s\xa0]*$/.test(a[c])||b.push(H(G(a[c])))}return b},J=function(a,b){return(a%b+b)%b},K=function(a,b,c,d){d=void 0===d?1:d;return J(a+("left"==b||"backwards"==b?-d:d),c)};var L=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},M=function(a){this.f=a;this.i=null;this.W=!0;this.v=!1};
M.prototype.play=function(a,b,c){var d=this;b=void 0===b?"forwards":b;if(this.f.frameCount&&null==this.i){if(c){var e=Math.floor(a/c);a=c}else e=this.f.frameCount,a/=e;var f=[],h=L(this.f);c=h;for(var k=0;k<e;k++){if(0<k||!this.W)c=K(c,b,this.f.frameCount);f.push(c)}b=function(){if(f.length){var v=f.shift();d.v=!0;d.f.goToFrame(v+1);d.v=!1;z("frameautoplayed",d.f,{id:v+1})}else d.stop(!0),d.f.goToFrame(h+1)};this.i=window.setInterval(b,a);setTimeout(b)}};
M.prototype.stop=function(a){a=void 0===a?!1:a;!this.v&&this.i&&(window.clearInterval(this.i),A("autoplayended",this.f,{completed:a}),this.i=null)};var N=["pause-front-media","resume-next-media"],O=function(){var a=HTMLElement.call(this)||this;a.frames=[];a.a=null;a.b=0;a.l=1;a.F=new M(a);a.V=!1;a.X=!1;return a};w(O,HTMLElement);O.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.V="true"==c;break;case "resume-next-media":this.X="true"==c}};O.prototype.gwdIsLoaded=function(){return!0};O.prototype.gwdLoad=function(){};
O.prototype.goToFrame=function(a){this.stopRotation();0!=this.b&&(a>this.b?a=this.b:1>a&&(a=1),this.a=a-1)};var P=function(a,b,c,d){if(null!=a.a){var e=K(a.a,b,a.l*Math.ceil(a.b/a.l),a.l);!d&&("forwards"==b&&e<a.a||"backwards"==b&&e>a.a)||a.goToFrame(e+1,c)}};g=O.prototype;g.goBackwards=function(a,b){P(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};g.goForwards=function(a,b){P(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};g.rotateOnce=function(a,b){this.F.play(void 0===a?0:a,b)};
g.stopRotation=function(){this.F.stop()};g.getFrame=function(a){if(0!=this.b)return this.frames[a-1]};var Q=function(a,b,c){z(b,a,{id:c||a.currentIndex})};n.Object.defineProperties(O.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.b?this.a+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.l}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.b}}});
n.Object.defineProperties(O,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return N}}});var R=["images","wrap","pause-front-media","resume-next-media"],S=function(){var a=O.call(this)||this;a.B=!1;a.c=null;a.D=0;a.h=null;a.N=a.T.bind(a);a.M=a.U.bind(a);a.L=a.S.bind(a);a.u=z.bind(null,"firstinteraction",a);a.J=a.P.bind(a);a.K=C(a.R.bind(a));a.s=[];a.H=0;a.g=-1;a.m=null;a.G=!1;a.j=!1;a.o=null;a.A=!1;a.I=!1;return a};w(S,O);g=S.prototype;
g.connectedCallback=function(){if(!this.A){var a=document.createElement("gwd-gesture");a.className="gesture";this.h=a;this.A=!0;this.I&&T(this)}this.h.addEventListener("trackstart",this.N,!1);this.h.addEventListener("track",this.M,!1);this.h.addEventListener("tap",this.L,!1);this.gwdIsLoaded()||((a=F(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());window.addEventListener("resize",this.K,!1)};
g.disconnectedCallback=function(){window.removeEventListener("resize",this.K,!1);var a=this.h;a.removeEventListener("trackstart",this.N,!1);a.removeEventListener("track",this.M,!1);a.removeEventListener("tap",this.L,!1);-1!=this.g&&(U(this,this.g),V(this))};
g.attributeChangedCallback=function(a,b,c,d){switch(a){case "images":V(this);this.G=!0;this.b=0;this.a=-1;this.frames=I(c);T(this);break;case "wrap":this.j=this.hasAttribute("wrap");break;default:O.prototype.attributeChangedCallback.call(this,a,b,c,d)}};
g.goToFrame=function(a,b,c){b=void 0===b?"slide":b;var d=a-1;V(this);if(0<=d&&d<this.frameCount&&d!=(-1!=this.g?this.g:this.a)){if(!c){c=this.a;var e=Math.abs(d-c);c=d>c==(!this.j||this.frameCount/2>e)?"forwards":"backwards"}Q(this,"frameactivated",a);this.C(K(this.a,c,this.frameCount),d,b,c,300)}};
g.rotateOnce=function(a,b){var c=this;V(this);var d=a&&b&&"string"==typeof a&&"number"==typeof b,e=(d?a:b)||"forwards",f=(d?b:a)||300*this.frameCount;if(1<this.frameCount){var h=this.a,k=K(this.a,e,this.frameCount);y(function(){c.C(k,h,"slide",e,f/c.frameCount,!0)},0)}};g.stopRotation=function(){V(this)};g.gwdIsLoaded=function(){return this.B};
g.gwdLoad=function(){if(!this.B&&!this.c){if(this.G)var a=I(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;T(this)}};
var T=function(a){if(a.A){for(;a.firstChild;)a.removeChild(a.firstChild);a.c&&a.c.removeEventListener("pageload",a.J,!1);for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d],f=void 0;f=void 0===f?!1:f;for(var h=0;h<D.length;h++){var k=D[h]+"user-select";var v=(f?D[h]:"")+"none";e.style.setProperty(k,v)}e.classList.add("frame");c.appendChild(e)}B(c,c.gwdLoad.bind(c));a.c=c;a.c.addEventListener("pageload",a.J,!1);a.appendChild(a.h);a.appendChild(a.c)}else a.I=!0};
g=S.prototype;g.P=function(a){this.c===a.target&&(x(this.frames,this.clientWidth,this.clientHeight),this.B=!0,this.removeChild(this.c),this.b=this.frames.length,this.s=[],this.H=this.frameCount,U(this,0),this.c=null,z("imagesloaded",this),z("allframesloaded",this),this.hasAttribute("autoplay")&&y(this.rotateOnce.bind(this),0),z("ready",this))};g.R=function(){x(this.frames,this.clientWidth,this.clientHeight)};g.T=function(){V(this);0<this.frameCount&&(this.D=this.a)};
g.U=function(a){this.frameCount&&(this.u&&(this.u(),this.u=null),a=Math.round(a.dx/50),a=this.j?J(this.D+a,this.frameCount):Math.max(0,Math.min(this.frameCount-1,this.D+a)),this.a!=a&&this.frames[a]&&(Q(this,"frameactivated",a+1),U(this,a)))};g.S=function(){this.frameCount&&Q(this,"frametap")};var U=function(a,b){if(a.a!=b&&a.frames[b]){a.a=b;var c=a.o;a.o=a.frames[b];a.appendChild(a.o);c&&a.removeChild(c);Q(a,"frameshown");a.s[b]||(a.s[b]=!0,--a.H||A("allframesviewed",a))}};
S.prototype.C=function(a,b,c,d,e,f){f=void 0===f?!1:f;"none"==c&&(a=b);U(this,a);f&&Q(this,"frameactivated",a+1);a!=b?(this.g=b,a=K(a,d,this.frameCount),this.m=y(this.C.bind(this,a,b,c,d,e,f),e)):(this.m=null,this.g=-1)};var V=function(a){-1!=a.g&&(window.clearTimeout(a.m),a.m=null,a.g=-1,Q(a,"frameactivated",a.a))};S.prototype.getFrame=function(a){return this.frames[a-1]};S.prototype.goForwards=function(){var a=J(this.a+1,this.frameCount);!this.j&&a<this.a||this.goToFrame(a+1)};
S.prototype.goBackwards=function(){var a=J(this.a-1,this.frameCount);!this.j&&a>this.a||this.goToFrame(a+1)};n.Object.defineProperties(S,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return R}}});customElements.define("gwd-360gallery",S);}).call(this);
