(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var c="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={m:!0},l={};try{l.__proto__=k;h=l.m;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var m=g,n=this||self,q=function(a,b){function f(){}f.prototype=b.prototype;a.s=b.prototype;a.prototype=new f;a.prototype.constructor=a;a.u=function(d,e,J){for(var w=Array(arguments.length-2),p=2;p<arguments.length;p++)w[p-2]=arguments[p];return b.prototype[e].apply(d,w)}};function r(a){if(Error.captureStackTrace)Error.captureStackTrace(this,r);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(r,Error);r.prototype.name="CustomError";var t=function(a,b){a=a.split("%s");for(var f="",d=a.length-1,e=0;e<d;e++)f+=a[e]+(e<b.length?b[e]:"%s");r.call(this,f+a[d])};q(t,r);t.prototype.name="AssertionError";var u=function(a,b,f){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new t(""+d,e||[]);}return a},v=function(a,b){throw new t("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var z=function(a,b){this.c=a===x&&b||"";this.l=y};z.prototype.g=!0;z.prototype.f=function(){return this.c};z.prototype.toString=function(){return"Const{"+this.c+"}"};var y={},x={};var A=new z(x,"_newtab");var C=function(a,b){this.b=b===B?a:""};C.prototype.g=!0;C.prototype.f=function(){return this.b.toString()};C.prototype.toString=function(){return"SafeUrl{"+this.b+"}"};var D=function(a){if(a instanceof C&&a.constructor===C)return a.b;var b=typeof a;v("expected object of type SafeUrl, got '"+a+"' of type "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null"));return"type_error:SafeUrl"},E=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,B={};var F=function(){var a=HTMLElement.call(this)||this;a.h=!1;a.j=a.o.bind(a);a.i=null;return a},G=HTMLElement;F.prototype=c(G.prototype);F.prototype.constructor=F;if(m)m(F,G);else for(var H in G)if("prototype"!=H)if(Object.defineProperties){var I=Object.getOwnPropertyDescriptor(G,H);I&&Object.defineProperty(F,H,I)}else F[H]=G[H];F.s=G.prototype;
F.prototype.connectedCallback=function(){var a=this;this.h||(document.body.style.opacity="0");setTimeout(function(){a.a=a.querySelector("gwd-pagedeck");window.addEventListener("resize",a.j,!1)},0)};F.prototype.disconnectedCallback=function(){window.removeEventListener("resize",this.j,!1)};F.prototype.initAd=function(){this.h=!0;document.body.style.opacity="";var a=void 0===a?null:a;var b=document.createEvent("CustomEvent");b.initCustomEvent("adinitialized",!0,!0,a);this.dispatchEvent(b);this.goToPage()};
F.prototype.goToPage=function(a,b,f,d,e){if(a=void 0!=a?this.a.getPage(a):this.a.getDefaultPage())a=this.a.getOrientationSpecificPage(window.innerHeight>=window.innerWidth?1:2,a.id),void 0!=b?this.a.goToPage(a.id,b,f,d,e):this.a.goToPage(a.id)};F.prototype.o=function(){var a=window.innerHeight>=window.innerWidth?1:2;this.i!=a&&(this.i=a,(a=this.a.getPage(Number(this.a.currentIndex)))&&this.goToPage(a.id))};
F.prototype.exit=function(a,b,f){b=void 0===b?!1:b;a instanceof C||a instanceof C||(a="object"==typeof a&&a.g?a.f():String(a),u(E.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new C(a,B));if(A instanceof z)if(A instanceof z&&A.constructor===z&&A.l===y)var d=A.c;else v("expected object of type Const, got '"+A+"'"),d="type_error:Const";else d=A||"";n.open(D(a),d);b&&this.goToPage(f)};customElements.define("gwd-genericad",F);}).call(this);
